---
- name: LSHELL | Clone the repository
  ansible.builtin.git:
    repo: "{{ classyllama_lshell_repo_url }}"
    dest: "/root/lshell-{{ classyllama_lshell_version }}"
    version: "{{ classyllama_lshell_version }} "

- name: LSHELL | Installation
  ansible.builtin.command:
    cmd: python setup.py install --no-compile --install-scripts=/usr/bin/
  args:
    chdir: "/root/lshell-{{ classyllama_lshell_version }}"
  ignore_errors: '{{ ansible_check_mode }}'

- name: LSHELL | Add to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /usr/bin/lshell

- name: LSHELL | Upload configuration file
  ansible.builtin.template:
    src: lshell.conf.j2
    dest: "/etc/lshell.conf"
    owner: root
    group: root
    mode: 0640
